/**
 * @swagger
 * components
 *      schemas:
 *          User:
 *              type: object
 *              required:
 *                  - email
 *                  - password
 *                  - name
 *                  - lang
 *                  - langInteface
 *              properties:
 *                  _id:
 *                      type: string   
 *                      description: the autogenerated id of user
 *                  email:
 *                      type: string
 *                      description: the user's email
 *                  name:
 *                      type: string
 *                      description: the user's name
 *                  token:
 *                      type: string
 *                      description: the user's api token
 *                  password: 
 *                      type: string
 *                      description: the user's password
 *                  lang: 
 *                      type: string
 *                      description: the user's selected lang
 *                  langInterface:
 *                      type: string     
 *                      description: the user's interface lang   
 *              example:
 *                  _id: askjgqeb1i2eqwnbemnsd
 *                  email: example@mail.ru
 *                  name: Jhon
 *                  token: as12837jhasfkj8912uhkaas
 *                  password: 123456
 *                  lang: en
 *                  langInterface: es
 *          errorDetails:
 *              type: object
 *              properties:
 *                  value:
 *                      type: string
 *                      description: value from client
 *                  msg: 
 *                      type: string
 *                      description: detail of error of field
 *                  param:
 *                      type: string
 *                      description: name of param from client
 *                  location: 
 *                      type: string
 *                      default: body
 *              example:
 *                  value: example.ru
 *                  msg: Неверный формат email
 *                  param: email
 *                  location: body    
 */